# Generated by Django 3.1.1 on 2020-11-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoalbum',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='photoalbums.photoalbum'),
        ),
    ]
