# Generated by Django 3.1.1 on 2020-11-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0002_auto_20201102_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='picture',
        ),
    ]
