# Generated by Django 3.1.1 on 2020-11-02 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbums', '0003_auto_20201102_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='image_dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='image_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
