# Generated by Django 3.1.1 on 2020-11-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0004_auto_20201102_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
