# Generated by Django 3.1.1 on 2020-11-02 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbums', '0005_image_is_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_avatar',
        ),
        migrations.AddField(
            model_name='image',
            name='avatar_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_avatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
