# Generated by Django 3.1.1 on 2020-11-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0006_auto_20201102_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='avatar_of',
        ),
    ]
