# Generated by Django 3.1.3 on 2020-11-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0009_auto_20201104_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='photoalbums.photoalbum'),
        ),
    ]
