# Generated by Django 3.1.1 on 2020-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='Body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Attach an image')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
