# Generated by Django 3.1.3 on 2020-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20201030_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
