# Generated by Django 3.1.3 on 2020-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20201117_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
