# Generated by Django 3.1.3 on 2020-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
