# Generated by Django 3.1.3 on 2020-11-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0007_auto_20201117_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
