# Generated by Django 3.1.3 on 2020-11-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chat_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='to_user',
        ),
    ]
