# Generated by Django 3.1.3 on 2020-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_message_nested_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=100, verbose_name='Body'),
        ),
    ]
