# Generated by Django 3.1.3 on 2020-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20201120_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='nested_messages',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Attach an image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Body'),
        ),
    ]
