# Generated by Django 3.1.1 on 2020-10-30 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Full Name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('gender', models.BooleanField(null=True, verbose_name='Gender')),
                ('following', models.CharField(blank=True, max_length=254, null=True, verbose_name='Following')),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('about_me', models.TextField(blank=True, max_length=5000, null=True, verbose_name='About me')),
                ('favourite_music', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Favourite music')),
                ('favourite_books', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Favourite books')),
                ('favourite_movies', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Favourite movies')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by_user', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
