# Generated by Django 3.1.3 on 2020-11-18 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20201110_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
