# Generated by Django 3.1.3 on 2020-11-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_user_subscribed_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscribed_to',
            new_name='subscribers',
        ),
    ]
