# Generated by Django 3.1.3 on 2020-11-18 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20201118_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
