# Generated by Django 3.1.3 on 2020-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_message_nested_messages'),
        ('user_profile', '0014_auto_20201118_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages_to_resend',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_resending', to='chats.Message'),
        ),
    ]
