# Generated by Django 3.1.3 on 2020-11-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_user_messages_to_resend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages_to_resend',
        ),
    ]
