# Generated by Django 3.1.3 on 2020-11-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201030_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_avatar',
            new_name='image',
        ),
    ]
